/** Re-export all constants from a single entry point */
export { personalInfo } from './personal'
export { navLinks } from './navigation'
export type { NavLink } from './navigation'
export { socialLinks } from './socials'
export type { SocialLink } from './socials'
export { skillCategories, softSkills } from './skills'
export type { Skill, SkillCategory, SoftSkill } from './skills'
export { projects, projectCategories } from './projects'
export type { Project } from './projects'
export { education, experience } from './qualification'
export type { TimelineItem } from './qualification'
export { aboutStats } from './about'
export type { Stat } from './about'
